#185106776 update password
atlp-rwanda/falcons-ec-fe pull request #18
Opened 2023-05-25 08:48 UTC by Rutarenzi

### What does this PR do?

- This PR implements the Update User's password feature
### Description of Task to be completed?
- Users should be able to update passwords by providing old and new passwords.
-
How should this be manually tested?

- Upon user logging in he/she can update the password, navigate the user profile, and click security. provide old and new passwords. 

### Any background context you want to provide?
N/A
### What are the relevant pivotal tracker id and link?

Tracker: #185106776
https://www.pivotaltracker.com/story/show/185106776

Screenshots (if appropriate)

## figma
![figmafalcon](https://github.com/atlp-rwanda/falcons-ec-fe/assets/88782915/aba7bd5e-38e9-449c-b137-2f41455eb0bc)
## implementation
![impliment](https://github.com/atlp-rwanda/falcons-ec-fe/assets/88782915/d1946142-5f57-4a89-8b6f-106fe813cfea)

2023-05-25 10:14 UTC, rwamugema requested changes

2023-05-25 10:14 UTC, rwamugema commented on src/App.jsx
> +    children: [{ path: '/update-password', element: <UpdatePassword/>}]
you can this in Layout above.

2023-05-25 11:31 UTC, fab-ryan commented on src/views/updatePswd.jsx
> +    };
you need to have state that checks if update is loading

2023-05-25 11:32 UTC, fab-ryan reviewed
change that then you can let me know

2023-06-07 13:58 UTC, fab-ryan approved these changes

2023-06-08 14:29 UTC, dean-daryl approved these changes

2023-06-08 14:46 UTC, rwamugema approved these changes

2023-06-20 11:55 UTC, merged