#185106764 Set Up React Router
atlp-rwanda/falcons-ec-fe pull request #2
Opened 2023-05-07 12:00 UTC by dean-daryl

#### What does this PR do?

- Sets Up React Router
#### Description of Task 
Install and configure the router creating a dummy route for login and the "/" page to test the configuration.
Create a components and views file structure where view pages are in the views folder but individual components are in the components folder
#### How should this be manually tested?
 clone the project and use the terminal to start the development server by "npm run dev" and run localhost:3000
#### Any background context you want to provide?
 none
#### What are the relevant pivotal tracker/Trello stories?
 Tracker: 185106764
#### Screenshots (if appropriate)
 none
#### Questions:
 none

2023-05-07 13:28 UTC, fab-ryan commented on src/main.jsx
> +    </Router>
we will not have this Layout all the time use Outlet component to differentiate  different layouts

2023-05-07 13:31 UTC, fab-ryan requested changes
Do research on outlet in react-router dom and learn how to create different Layout

2023-05-08 13:45 UTC, kirengaboris approved these changes

2023-05-08 13:47 UTC, masterchief-00 approved these changes

2023-05-08 13:54 UTC, fab-ryan approved these changes

2023-05-08 14:13 UTC, merged