# 185106775 Seller Two Factor Auth
atlp-rwanda/falcons-ec-fe pull request #26
Opened 2023-06-01 04:18 UTC by Jmukakalisa

**What does this PR do?**

- This PR implements the two factor authentication feature

**Description of Task to be completed?**

- A seller should be able to authenticate with otp code

**How should this be manually tested?**

- Clone this project run the script "npm run dev" then go to ''signin" then signin as a seller ==> "users/verify"

**Any background context you want to provide?**

- N/A

**What are the relevant pivotal tracker/Trello stories?**

- Tracker: 185106775

**Screenshot**

<img width="1440" alt="Screenshot 2023-06-01 at 05 45 17" src="https://github.com/atlp-rwanda/falcons-ec-fe/assets/90443432/c9b36628-d5b9-4c53-a171-e0ad0b5e3757">

<img width="1440" alt="Screenshot 2023-06-01 at 05 45 27" src="https://github.com/atlp-rwanda/falcons-ec-fe/assets/90443432/0eec91b6-6e5d-4399-9149-47e201a219a5">

https://github.com/atlp-rwanda/falcons-ec-fe/assets/90443432/34be9bf8-294f-4bb7-aaea-63bd3084b9a2

**Questions**

- None

2023-06-01 08:00 UTC, fab-ryan commented on src/redux/slices/user/twoFactorAuth.js
> +      return response.data;
when verification is done you should destruct token from the response and store it as token

2023-06-01 08:01 UTC, fab-ryan requested changes
check how your token can be stored without login again

2023-06-01 13:25 UTC, kirengaboris approved these changes

2023-06-01 14:14 UTC, kirengaboris approved these changes

2023-06-01 14:16 UTC, rwamugema approved these changes

2023-06-02 11:12 UTC, fab-ryan commented on src/views/twoFactorAuth.jsx
> +              />
there isn't a property called OTP in Input type as attributes value

2023-06-02 11:21 UTC, fab-ryan requested changes
correct that mistake then  I will merge it

2023-06-02 12:20 UTC, fab-ryan approved these changes

2023-06-02 12:20 UTC, merged